Basic Python

 1.Split this string

In [2]:
sakthi = "Hi there Samy!"
sakthi = "Hi there Samy!"
sakthi.split()


['Hi', 'there', 'Samy!']

2. Use .format() to print the following string.
Output should be: The size of Earth is 12742 kilometers.

In [5]:
asteroid = "Earth"
size = 12742
asteroid = "Earth"
size = 12742
'The size of {} is {} kilometers.'.format(asteroid,size)

'The size of Earth is 12742 kilometers.'

3. In this nest dictionary grab the word "hello"

In [6]:
s = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'welcome']}]}]}
s = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'welcome']}]}]}
s['k1'][3]['tricky'][3]['target'][3]

'welcome'

Numpy

In [7]:
import numpy as np

4.1 Create an array of 10 zeros?

4.2 Create an array of 10 fives?

In [27]:
import numpy as ny
ny.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
import numpy as ny
ny.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Create an array of all the even integers from 20 to 35

In [11]:
ny.arange(20,36,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

6. Create a 4x4 matrix with values ranging from 0 to 16

In [13]:
ny.arange(0,16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

7. Concatenate a and b

   a = np.array([7 ,8 ,9 ]), b = np.array([4, 5, 6])

In [14]:
a = ny.array([7,8,9])
b = ny.array([4, 5, 6])
ny.concatenate([a,b])

array([7, 8, 9, 4, 5, 6])

Pandas

8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd
import pandas as pd 
data ={'Name':['sakthi','kalai'],'Age':[20,19],'Dept':['CSE','ECE']}
df=pd.DataFrame(data) 
print(df)

     Name  Age Dept
0  sakthi   20  CSE
1   kalai   19  ECE


9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023


In [ ]:
ds=ps.DataFrame(ps.date_range(start='1/1/2023',end='2/10/2023'),columns=['dates'])
ds

10. Create 2D list to DataFrame

  lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
ds1=ps.DataFrame(lists)
ds1